name: Run Hive Fill

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout execution-spec-tests-gnosis
        uses: actions/checkout@v4

      - name: Install Go (for Hive)
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Build and install Hive
        run: |
          git clone https://github.com/gnosischain/hive.git
          cd hive
          go install ./...
          cd ..

      - name: Start Hive in background
        run: |
          nohup ~/go/bin/hive > hive.log 2>&1 &

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH  # uv installs here on Ubuntu

      - name: Bootstrap Python and install deps
        run: |
          pip install uv
          uv python install 3.11
          uv python pin 3.11
          uv sync --all-extras
          uv pip install solc-select
          uv run solc-select use 0.8.24 --always-install

      - name: Run fill
        run: uv run fill ./tests/gnosis/test_gnosis_blockchain.py --fork Prague --clean -c pytest-gnosis.ini --gnosis

      - name: Run test against Geth
        env:
          HIVE_SIMULATOR: http://127.0.0.1:3000
        run: uv run consume engine -v --input fixtures/blockchain_tests_engine/gnosis/gnosis_blockchain

