name: Run Hive Fill

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:24.0.2
        options: --privileged
    steps:
      - name: Checkout execution-spec-tests-gnosis
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install uv
        run: |
          pip install uv

      - name: Install project dependencies
        run: |
          uv pip install -r requirements.txt
          uv pip install -e .

      - name: Install Go (for Hive)
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Checkout and build Hive
        run: |
          git clone https://github.com/gnosischain/hive.git
          cd hive
          go install ./...
          cd ..

      - name: Start Hive (in background)
        run: |
          nohup ~/go/bin/hive > hive.log 2>&1 &

      - name: Run fill
        run: |
          uv run fill ./tests/gnosis/test_gnosis_blockchain.py --fork Prague --clean -c pytest-gnosis.ini --gnosis

